name: Build and Deploy LaTeX CV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          compiler: pdflatex
          pre_compile: |
            apt-get update
            apt-get install -y texlive-latex-base texlive-bibtex-extra  # Add any other necessary packages

      - name: Build LaTeX CV
        run: pdflatex -pdf -file-line-error -halt-on-error -interaction=nonstopmode cv.tex

      - name: Move artifacts
        run: |
          mv cv.pdf ./my-cv.pdf
          mv cv.png ./my-cv.png

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cv-artifact
          path: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the build job is completed before deploying

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: cv-artifact
          path: ./

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
